import { configureFonts, MD3DarkTheme, MD3LightTheme, MD3Theme } from 'react-native-paper';

const fontConfig = {
	default: {
		fontFamily: 'Manrope-Regular',
		fontWeight: '400',
		letterSpacing: 0,
	},
	displaySmall: {
		fontFamily: 'Manrope-Regular',
		fontSize: 36,
		fontWeight: '400',
		letterSpacing: 0,
		lineHeight: 44,
	},
	displayMedium: {
		fontFamily: 'Manrope-Bold',
		fontSize: 45,
		letterSpacing: 0,
		lineHeight: 52,
	},
	displayLarge: {
		fontFamily: 'Manrope-Regular',
		fontSize: 57,
		fontWeight: '400',
		letterSpacing: 0,
		lineHeight: 64,
	},
	headlineSmall: {
		fontFamily: 'Manrope-Regular',
		fontSize: 24,
		fontWeight: '400',
		letterSpacing: 0,
		lineHeight: 32,
	},
	headlineMedium: {
		fontFamily: 'Manrope-Regular',
		fontSize: 28,
		fontWeight: '400',
		letterSpacing: 0,
		lineHeight: 36,
	},
	headlineLarge: {
		fontFamily: 'Manrope-Medium',
		fontSize: 32,
		fontWeight: '400',
		letterSpacing: 0,
		lineHeight: 40,
	},
	titleSmall: {
		fontFamily: 'Manrope-Regular',
		fontSize: 14,
		fontWeight: '500',
		letterSpacing: 0.1,
		lineHeight: 20,
	},
	titleMedium: {
		fontFamily: 'Manrope-Medium',
		fontSize: 16,
		fontWeight: '500',
		letterSpacing: 0.15,
		lineHeight: 24,
	},
	titleLarge: {
		fontFamily: 'Manrope-Medium',
		fontSize: 22,
		fontWeight: '400',
		letterSpacing: 0,
		lineHeight: 28,
	},
	labelSmall: {
		fontFamily: 'Manrope-Medium',
		fontSize: 11,
		fontWeight: '500',
		letterSpacing: 0.5,
		lineHeight: 16,
	},
	labelMedium: {
		fontFamily: 'Manrope-SemiBold',
		fontSize: 12,
		fontWeight: '500',
		letterSpacing: 0.5,
		lineHeight: 16,
	},
	labelLarge: {
		fontFamily: 'Manrope-SemiBold',
		fontSize: 14,
		fontWeight: '500',
		letterSpacing: 0.1,
		lineHeight: 20,
	},
	bodySmall: {
		fontFamily: 'Manrope-Medium',
		fontSize: 12,
		fontWeight: '400',
		letterSpacing: 0.4,
		lineHeight: 16,
	},
	bodyMedium: {
		fontFamily: 'Manrope-Regular',
		fontSize: 14,
		fontWeight: '400',
		letterSpacing: 0.25,
		lineHeight: 20,
	},
	bodyLarge: {
		fontFamily: 'Manrope-Medium',
		fontSize: 16,
		fontWeight: '400',
		letterSpacing: 0.15,
		lineHeight: 24,
	},
} as const;

export type AdditionalColors = {
	additionalColors: {
		green: string;
		greenOpacity: string;
		redOpacity: string;
		ripple: string;
	};
};

export const DarkTheme: MD3Theme & AdditionalColors = {
	...MD3DarkTheme,
	colors: {
		primary: '#34548A',
		onPrimary: '#C0CAF5',
		primaryContainer: '#34548A',
		onPrimaryContainer: '#C0CAF5',
		secondary: '#24283B',
		onSecondary: '#C0CAF5',
		secondaryContainer: '#24283B',
		onSecondaryContainer: '#C0CAF5',
		tertiary: '#7DCFFF',
		onTertiary: '#343B58',
		tertiaryContainer: '#7DCFFF',
		onTertiaryContainer: '#343B58',
		error: '#F7768E',
		onError: '#C0CAF5',
		errorContainer: '#F7768E',
		onErrorContainer: '#C0CAF5',
		background: '#16161F',
		onBackground: '#C0CAF5',
		surface: '#1A1B26',
		onSurface: '#C0CAF5',
		surfaceVariant: '#1A1B26',
		onSurfaceVariant: '#565F89',
		outline: '#34548A',
		outlineVariant: '#34548A',
		shadow: '#000000',
		scrim: '#000000',
		inverseSurface: '#1A1B26',
		inverseOnSurface: '#C0CAF5',
		inversePrimary: '#34548A',
		elevation: {
			level0: 'transparent',
			level1: '#1A1B26',
			level2: '#1A1B26',
			level3: '#1A1B26',
			level4: '#1A1B26',
			level5: '#1A1B26',
		},
		surfaceDisabled: '#1A1B267F',
		onSurfaceDisabled: '#C0CAF561',
		backdrop: '#312F3866',
	},
	additionalColors: {
		green: '#9ECE6A',
		greenOpacity: '#9ECE6A4C',
		redOpacity: '#F7768E4C',
		ripple: '#C0CAF57F',
	},
	fonts: configureFonts({ config: fontConfig }),
};

export const LightTheme: MD3Theme & AdditionalColors = {
	...MD3LightTheme,
	colors: {
		primary: '#7AA2F7',
		onPrimary: '#343B58',
		primaryContainer: '#7AA2F7',
		onPrimaryContainer: '#343B58',
		secondary: '#B5BEE8',
		onSecondary: '#343B58',
		secondaryContainer: '#B5BEE8',
		onSecondaryContainer: '#343B58',
		tertiary: '#7DCFFF',
		onTertiary: '#343B58',
		tertiaryContainer: '#7DCFFF',
		onTertiaryContainer: '#343B58',
		error: '#8C4351',
		onError: '#343B58',
		errorContainer: '#8C4351',
		onErrorContainer: '#343B58',
		background: '#CBCCD2',
		onBackground: '#343B58',
		surface: '#D5D6DB',
		onSurface: '#343B58',
		surfaceVariant: '#D5D6DB',
		onSurfaceVariant: '#9699A3',
		outline: '#7AA2F7',
		outlineVariant: '#7AA2F7',
		shadow: '#000000',
		scrim: '#000000',
		inverseSurface: '#D5D6DB',
		inverseOnSurface: '#343B58',
		inversePrimary: '#7AA2F7',
		elevation: {
			level0: 'transparent',
			level1: '#D5D6DB',
			level2: '#D5D6DB',
			level3: '#D5D6DB',
			level4: '#D5D6DB',
			level5: '#D5D6DB',
		},
		surfaceDisabled: '#D5D6DB7F',
		onSurfaceDisabled: '#343B5861',
		backdrop: '#312F3866',
	},
	additionalColors: {
		green: '#62843E',
		greenOpacity: '#9ECE6A4C',
		redOpacity: '#F7768E4C',
		ripple: '#343B5880',
	},
	fonts: configureFonts({ config: fontConfig }),
};
